// src/commands/music/tone.rs
use serenity::all::{
    Command, CommandInteraction, Context, CreateCommand, CreateInteractionResponse,
    CreateInteractionResponseFollowup, CreateInteractionResponseMessage, GuildId,
};

/// Register /tone globally using the batch API (stable on serenity 0.12.2).
pub async fn register_tone_cmd(ctx: &Context) {
    let cmds = vec![
        CreateCommand::new("tone")
            .description("Join your voice channel and play a short test tone"),
    ];

    if let Err(err) = Command::set_global_commands(&ctx.http, cmds).await {
        eprintln!("[/tone] failed to register: {err}");
    }
}

/// Optional: instant dev registration to ONE guild (appears immediately).
/// Call this instead of register_tone_cmd in your Ready handler during testing.
#[allow(dead_code)]
pub async fn register_tone_guild_cmd(ctx: &Context, guild_id: GuildId) {
    let cmds = vec![
        CreateCommand::new("tone")
            .description("Join your voice channel and play a short test tone"),
    ];

    if let Err(err) = Command::set_guild_commands(&ctx.http, guild_id, cmds).await {
        eprintln!("[/tone] failed to register (guild): {err}");
    }
}

/// /tone: joins your VC, plays a tiny MP3 with ffmpeg, then leaves.
/// Requires:
///   - client built with `.register_songbird()`
///   - ffmpeg binary present in the runtime (PATH)
pub async fn run_tone(ctx: &Context, cmd: &CommandInteraction) {
    // Respond immediately so Discord doesn't show "did not respond"
    let _ = cmd
        .create_response(
            &ctx.http,
            CreateInteractionResponse::Message(
                CreateInteractionResponseMessage::new()
                    .content("🎧 Joining and playing a short test tone...")
                    .ephemeral(true),
            ),
        )
        .await;

    // Must be in a guild
    let Some(guild_id) = cmd.guild_id else {
        let _ = cmd
            .create_followup(
                &ctx.http,
                CreateInteractionResponseFollowup::new()
                    .content("Run this in a server while you’re in a voice channel.")
                    .ephemeral(true),
            )
            .await;
        return;
    };

    // Need the caller's current voice channel
    let Some(guild) = guild_id.to_guild_cached(&ctx.cache) else {
        let _ = cmd
            .create_followup(
                &ctx.http,
                CreateInteractionResponseFollowup::new()
                    .content("Couldn’t read guild from cache yet. Try again in a few seconds.")
                    .ephemeral(true),
            )
            .await;
        return;
    };

    let Some(vc) = guild
        .voice_states
        .get(&cmd.user.id)
        .and_then(|vs| vs.channel_id)
    else {
        let _ = cmd
            .create_followup(
                &ctx.http,
                CreateInteractionResponseFollowup::new()
                    .content("Join a voice channel first, then run /tone.")
                    .ephemeral(true),
            )
            .await;
        return;
    };

    // Songbird manager (client must be built with `.register_songbird()`)
    let Some(manager) = songbird::get(ctx).await.map(|m| m.clone()) else {
        let _ = cmd
            .create_followup(
                &ctx.http,
                CreateInteractionResponseFollowup::new()
                    .content("Voice client (Songbird) isn’t available. Did you call `.register_songbird()`?")
                    .ephemeral(true),
            )
            .await;
        return;
    };

    // Join VC
    if let Err(e) = manager.join(guild_id, vc).await {
        let _ = cmd
            .create_followup(
                &ctx.http,
                CreateInteractionResponseFollowup::new()
                    .content(format!("Failed to join voice channel: {e}"))
                    .ephemeral(true),
            )
            .await;
        return;
    }

    // Simple public MP3; requires:
    //  - Cargo.toml: songbird = { version = "0.4.4", features = ["simd-json", "ffmpeg"] }
    //  - ffmpeg in the container/host PATH
    let test_url = "https://file-examples.com/storage/fe9a7a0e9a8d3a198b1b0aa/2017/11/file_example_MP3_700KB.mp3";

    // Fully-qualified + async helper
    match songbird::input::ffmpeg(test_url).await {
        Ok(src) => {
            if let Some(call) = manager.get(guild_id) {
                let mut handler = call.lock().await;
                handler.play_input(src);

                // Leave after ~7 seconds so the bot doesn't linger
                {
                    let manager = manager.clone();
                    tokio::spawn(async move {
                        tokio::time::sleep(std::time::Duration::from_secs(7)).await;
                        let _ = manager.remove(guild_id).await;
                    });
                }

                let _ = cmd
                    .create_followup(
                        &ctx.http,
                        CreateInteractionResponseFollowup::new()
                            .content("🔊 Playing! I’ll disconnect shortly.")
                            .ephemeral(true),
                    )
                    .await;
            } else {
                let _ = cmd
                    .create_followup(
                        &ctx.http,
                        CreateInteractionResponseFollowup::new()
                            .content("Joined, but couldn’t access the call handler.")
                            .ephemeral(true),
                    )
                    .await;
            }
        }
        Err(err) => {
            let _ = cmd
                .create_followup(
                    &ctx.http,
                    CreateInteractionResponseFollowup::new()
                        .content(format!("ffmpeg failed to start (is ffmpeg installed in the container?): {err}"))
                        .ephemeral(true),
                )
                .await;
        }
    }
}
